import React from 'react';

const ReceiptModal = ({ receiptGenerated, setReceiptGenerated }) => {
  const printReceipt = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <html>
        <head>
          <title>Payment Receipt</title>
          <style>
            body { font-family: Arial, sans-serif; padding: 40px; }
            .receipt { max-width: 500px; margin: 0 auto; border: 1px solid #ddd; padding: 20px; border-radius: 10px; }
            .header { text-align: center; border-bottom: 2px solid #333; padding-bottom: 10px; margin-bottom: 20px; }
            .logo { font-size: 24px; font-weight: bold; color: #0ea5e9; }
            .title { font-size: 18px; margin-top: 5px; }
            .details { margin: 20px 0; }
            .row { display: flex; justify-content: space-between; margin: 10px 0; padding: 5px 0; }
            .total { border-top: 2px solid #333; margin-top: 20px; padding-top: 10px; font-weight: bold; font-size: 18px; }
            .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #666; }
            button { margin-top: 20px; padding: 10px 20px; background: #0ea5e9; color: white; border: none; cursor: pointer; border-radius: 5px; }
          </style>
        </head>
        <body>
          <div class="receipt">
            <div class="header">
              <div class="logo">🏥 AppointPro</div>
              <div class="title">Payment Receipt</div>
            </div>
            <div class="details">
              <div class="row"><strong>Receipt No:</strong> <span>${receiptGenerated.id}</span></div>
              <div class="row"><strong>Date:</strong> <span>${receiptGenerated.date}</span></div>
              <div class="row"><strong>Patient Name:</strong> <span>${receiptGenerated.patientName}</span></div>
              <div class="row"><strong>Phone:</strong> <span>${receiptGenerated.patientPhone}</span></div>
              <div class="row"><strong>Email:</strong> <span>${receiptGenerated.patientEmail}</span></div>
              <div class="row"><strong>Service:</strong> <span>${receiptGenerated.service}</span></div>
              <div class="row"><strong>Appointment Date:</strong> <span>${receiptGenerated.appointmentDate}</span></div>
              <div class="row"><strong>Payment Method:</strong> <span>${receiptGenerated.paymentMethod}</span></div>
              <div class="row total"><strong>Amount Paid:</strong> <span>₹${receiptGenerated.amount}</span></div>
            </div>
            <div class="footer">
              <p>Thank you for choosing AppointPro!</p>
              <p>Generated by: ${receiptGenerated.generatedBy}</p>
            </div>
          </div>
          <div style="text-align: center;">
            <button onclick="window.print();setTimeout(()=>window.close(),500)">🖨️ Print Receipt</button>
          </div>
        </body>
      </html>
    `);
    printWindow.document.close();
  };

  const styles = {
    modalOverlay: { position: 'fixed', top: 0, left: 0, right: 0, bottom: 0, backgroundColor: 'rgba(0,0,0,0.5)', display: 'flex', alignItems: 'center', justifyContent: 'center', zIndex: 2000 },
    modalContent: { backgroundColor: 'white', padding: '24px', borderRadius: '16px', width: '400px', maxWidth: '90%' },
    modalTitle: { fontSize: '20px', fontWeight: 'bold', marginBottom: '20px' },
    receiptBox: { padding: '16px', backgroundColor: '#f8f9fa', borderRadius: '8px', marginBottom: '20px' },
    buttonGroup: { display: 'flex', gap: '12px' },
    saveBtn: { flex: 1, padding: '10px', backgroundColor: '#0ea5e9', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer' },
    cancelBtn: { flex: 1, padding: '10px', backgroundColor: '#ef4444', color: 'white', border: 'none', borderRadius: '8px', cursor: 'pointer' }
  };

  if (!receiptGenerated) return null;

  return (
    <div style={styles.modalOverlay} onClick={() => setReceiptGenerated(null)}>
      <div style={styles.modalContent} onClick={(e) => e.stopPropagation()}>
        <h2 style={styles.modalTitle}>🧾 Payment Receipt</h2>
        <div style={styles.receiptBox}>
          <div><strong>Receipt No:</strong> {receiptGenerated.id}</div>
          <div><strong>Date:</strong> {receiptGenerated.date}</div>
          <div><strong>Patient:</strong> {receiptGenerated.patientName}</div>
          <div><strong>Service:</strong> {receiptGenerated.service}</div>
          <div><strong>Amount:</strong> <span style={{ fontSize: '18px', color: '#10b981' }}>₹{receiptGenerated.amount}</span></div>
          <div><strong>Payment Method:</strong> {receiptGenerated.paymentMethod}</div>
          <hr style={{ margin: '12px 0' }} />
          <div><strong>Payment Status:</strong> <span style={{ color: '#10b981' }}>✅ Completed</span></div>
        </div>
        <div style={styles.buttonGroup}>
          <button style={styles.saveBtn} onClick={printReceipt}>🖨️ Print Receipt</button>
          <button style={styles.cancelBtn} onClick={() => setReceiptGenerated(null)}>Close</button>
        </div>
      </div>
    </div>
  );
};

export default ReceiptModal;